// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"cli-inventory/internal/models"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStockMovementRepositoryInterface creates a new instance of MockStockMovementRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockMovementRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockMovementRepositoryInterface {
	mock := &MockStockMovementRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStockMovementRepositoryInterface is an autogenerated mock type for the StockMovementRepositoryInterface type
type MockStockMovementRepositoryInterface struct {
	mock.Mock
}

type MockStockMovementRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockMovementRepositoryInterface) EXPECT() *MockStockMovementRepositoryInterface_Expecter {
	return &MockStockMovementRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStockMovementRepositoryInterface
func (_mock *MockStockMovementRepositoryInterface) Create(ctx context.Context, movement *models.StockMovement) (*models.StockMovement, error) {
	ret := _mock.Called(ctx, movement)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.StockMovement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.StockMovement) (*models.StockMovement, error)); ok {
		return returnFunc(ctx, movement)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.StockMovement) *models.StockMovement); ok {
		r0 = returnFunc(ctx, movement)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StockMovement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.StockMovement) error); ok {
		r1 = returnFunc(ctx, movement)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStockMovementRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStockMovementRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - movement *models.StockMovement
func (_e *MockStockMovementRepositoryInterface_Expecter) Create(ctx interface{}, movement interface{}) *MockStockMovementRepositoryInterface_Create_Call {
	return &MockStockMovementRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, movement)}
}

func (_c *MockStockMovementRepositoryInterface_Create_Call) Run(run func(ctx context.Context, movement *models.StockMovement)) *MockStockMovementRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.StockMovement
		if args[1] != nil {
			arg1 = args[1].(*models.StockMovement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockMovementRepositoryInterface_Create_Call) Return(stockMovement *models.StockMovement, err error) *MockStockMovementRepositoryInterface_Create_Call {
	_c.Call.Return(stockMovement, err)
	return _c
}

func (_c *MockStockMovementRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, movement *models.StockMovement) (*models.StockMovement, error)) *MockStockMovementRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}
