packages:
  cli-inventory/internal/service:
    interfaces:
      ProductRepositoryInterface:
        config:
          dir: internal/mocks
          mockname: MockProductRepository
      LocationRepositoryInterface:
        config:
          dir: internal/mocks
          mockname: MockLocationRepository
      StockRepositoryInterface:
        config:
          dir: internal/mocks
          mockname: MockStockRepository
      StockMovementRepositoryInterface:
        config:
          dir: internal/mocks
          mockname: MockStockMovementRepository
      ProductServiceInterface:
        config:
          dir: internal/mocks
          mockname: MockProductService
      LocationServiceInterface:
        config:
          dir: internal/mocks
          mockname: MockLocationService
      StockServiceInterface:
        config:
          dir: internal/mocks
          mockname: MockStockService
  cli-inventory/internal/db:
    interfaces:
      Querier:
        config:
          dir: internal/mocks
          mockname: MockQuerier
      DBTX:
        config:
          dir: internal/mocks
          mockname: MockDBTX