// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Location struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          int32              `json:"id"`
	Sku         string             `json:"sku"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Stock struct {
	ID         int32              `json:"id"`
	ProductID  int32              `json:"product_id"`
	LocationID int32              `json:"location_id"`
	Quantity   int32              `json:"quantity"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type StockMovement struct {
	ID             int32              `json:"id"`
	ProductID      int32              `json:"product_id"`
	FromLocationID pgtype.Int4        `json:"from_location_id"`
	ToLocationID   pgtype.Int4        `json:"to_location_id"`
	Quantity       int32              `json:"quantity"`
	MovementType   string             `json:"movement_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
