// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddStock(ctx context.Context, arg AddStockParams) (Stock, error)
	CreateLocation(ctx context.Context, name string) (Location, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error)
	CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error)
	DeleteLocation(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, id int32) error
	DeleteStock(ctx context.Context, arg DeleteStockParams) error
	GetLocationByID(ctx context.Context, id int32) (Location, error)
	GetLocationByName(ctx context.Context, name string) (Location, error)
	GetLowStock(ctx context.Context, quantity int32) ([]Stock, error)
	GetProductByID(ctx context.Context, id int32) (Product, error)
	GetProductBySKU(ctx context.Context, sku string) (Product, error)
	GetStockByLocation(ctx context.Context, locationID int32) ([]Stock, error)
	GetStockByProduct(ctx context.Context, productID int32) ([]Stock, error)
	GetStockByProductAndLocation(ctx context.Context, arg GetStockByProductAndLocationParams) (Stock, error)
	GetStockMovementsByLocation(ctx context.Context, fromLocationID pgtype.Int4) ([]StockMovement, error)
	GetStockMovementsByProduct(ctx context.Context, productID int32) ([]StockMovement, error)
	ListLocations(ctx context.Context) ([]Location, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListStockMovements(ctx context.Context) ([]StockMovement, error)
	RemoveStock(ctx context.Context, arg RemoveStockParams) (Stock, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error)
}

var _ Querier = (*Queries)(nil)
